# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Juzer Zarif
email: juzerapj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Computer Enginnering student at the University of Kansas, who likes audio equipment and movies. 
  Feel free to email me with any questions!  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://juzerzarif.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  juzerzarif

# Build settings
markdown: kramdown
